name: speech emotion recognizer
run-name: deploying model for ${{ github.actor }}
on:
  [push]
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    outputs:
      venv: ${{ steps.create_venv.outputs.venv }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Create venv
        id: create_venv
        run: |
          python -m venv ${{ runner.workspace }}/venv
          source ${{ runner.workspace }}/venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        env:
          PIP_CACHE_DIR: ${{ runner.workspace }}/.pip-cache
      - name: Cache Python
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}/venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

  predict:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Use venv from install_dependencies
        env:
          VIRTUAL_ENV: ${{ needs.install_dependencies.outputs.venv }}
        run: |
          source $VIRTUAL_ENV/../bin/activate
          python ./scripts/predict.py
