name: speech emotion recognizer
run-name: deploying model for ${{ github.actor }}
on:
  [push]
jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: Cache Python
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: python-3.9.5-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
  predict:
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: Predict
        run: |
          python ./scripts/predict.py
